src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @method string getUserIdentifier()
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $role = [];

    /**
     * @var string the hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): ?array
    {
        $role = $this->role;

        $role[] = "ROLE_USER";

        return array_unique($role);
    }


    public function setRoles(?array $role): self
    {
        $this->role = $role;

        return $this;
    }


    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword():string
    {
        return $this->password;
    }

    public function setPassword(string $password): User
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUsername(): string
    {
        return (string)$this->email;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function upVote():self
    {
        $this->votes++;
        return $this;
    }

    public function downVote():self
    {
        $this->votes--;
        return $this;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\App;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    private $hasher;
    public function __construct(UserPasswordHasherInterface $hasher)
    {
        $this->hasher = $hasher;
    }
    /**
     * @param UserRepository $userRepository
     * @return Response
     * @Route("/user", name="app_user_index")
     */
    public function index(UserRepository $Repository): Response
    {
        $loggedUser = $this->getUser();
        $user = $Repository->findAll();

        return $this->render('user/index.html.twig', [
            'users' => $user,
            'loggedUser' => $loggedUser,
        ]);
    }

    /**
     * @param User $user
     * @return Response
     * @Route("/user/{id}", name="app_user_show")
     */
    public function showOneUser(User $user): Response
    {
        return $this->render('user/user_show.html.twig', [
            'users' => $user,
        ]);
    }

    /**
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @Route("/user/{id}/delete", name="app_user_delete")
     */
    public function deleteUser(User $user, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($user);
        $entityManager->flush();

        return $this->redirectToRoute('app_user_index');
    }

    /**
     * @return Response
     * @Route("/user_new", name="app_user_new")
     */
    public function createNewUser():Response
    {
        return $this->render('user/user_new.html.twig');
    }

    /**
     * @param EntityManagerInterface $entityManager
     * @param Request $request
     * @return Response
     * @Route ("/register", name="app_user_register", methods={"POST"})
     */
    public function submitUser(EntityManagerInterface $entityManager, Request $request): Response
    {
        $user = new User();
        $user->setFirstname($request->request->get('fistName'))
             ->setLastname($request->request->get('lastName'))
             ->setEmail($request->request->get('email'))
            ->setRoles((array)$request->request->get('role'))
            ->setPassword($this->hasher->hashPassword($user, $request->request->get('password')));


        $entityManager->persist($user);
        $entityManager->flush();

        return $this->redirectToRoute('app_login');
    }

    /**
     * @param User $user
     * @return Response
     * @Route("/user/{id}/modify", name="app_user_modify")
     */
    public function modifyUser(User $user): Response
    {
        return $this->render('user/user_modify.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @param User $user
     * @param EntityManagerInterface $entityManager
     * @param Request $request
     * @return Response
     * @Route ("/user/{id}/update", name="app_user_update", methods={"POST"})
     */
    public function updateUser(User $user, EntityManagerInterface $entityManager, Request $request): Response
    {
        $user->setFirstname($request->request->get('fistName'))
            ->setLastname($request->request->get('lastName'))
            ->setEmail($request->request->get('email'))
            ->setRoles((array)$request->request->get('role'));


        $entityManager->flush();

        return $this->redirectToRoute('app_user_show', [
            'id' => $user->getId()
        ]);
    }


    /**
     * @param User $user
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @Route("/user/{id}/vote", name="app_user_vote", methods="POST")
     */
    public function userVote(User $user, Request $request, EntityManagerInterface $entityManager): Response
    {
        $vote = $request->request->get('vote');

        if ($vote === 'up'){
            $user->upVote();
        }
        if ($vote === 'down'){
            $user->downVote();
        }

        $entityManager->flush();
        return $this->redirectToRoute('app_ad', [
            'id' => $user->getId()
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
 {% if app.user %}
<div class="example-wrapper">
    <a href="{{ path('app_user_new') }}">create user</a>
    <ul>
        {% for user in users %}
            <li>{{ user.lastname ? user.lastname : null }} {{ user.firstname }} {{ user.email }}</li>
            <a href="{{ path('app_user_show', {id: user.id}) }}">
                show page
            </a>
            <a href="{{ path('app_user_modify', {id: user.id}) }}">
                update user
            </a>
        {% endfor %}
    </ul>
</div>
 {% endif %}
{% endblock %}

templates/user/user_modify.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <body class="text-center">
        <main class="container">
            <h1>New User</h1>
            <form class="d-flex flex-column justify-content-center align-items-center" action="{{ path('app_user_update', {id: user.id}) }}" method="post">
                <div class="mb-3">
                    <label class="form-label" for="firstName">first name</label>
                    <input class="from-control" id="firstName" name="fistName" value="{{ user.firstName|default('') }}">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="lastName">Last name</label>
                    <input class="from-control" id="lastName" name="lastName" value="{{ user.lastName|default('') }}">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="email">email</label>
                    <input class="from-control" type="email" id="email" name="email" value="{{ user.email|default('') }}">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="password">password</label>
                    <input class="from-control" type="password" id="password" name="password" value="">
                </div>
                <div class="mb-3">
                    <label class="form-check-label" for="role_admin">admin</label>
                    {% if 'ROLE_ADMIN' in user.roles %}
                        <input class="form-check-input" type="checkbox" value="ROLE_ADMIN" id="role_admin" name="role[]" checked>
                    {% else %}
                        <input class="form-check-input" type="checkbox" value="ROLE_ADMIN" id="role_admin" name="role[]">
                    {% endif%}
                    <label class="form-check-label" for="role_seller">seller</label>
                    {% if 'ROLE_SELLER' in user.roles %}
                        <input class="form-check-input" type="checkbox" value="ROLE_SELLER" id="role_seller" name="role[]" checked>
                    {% else %}
                        <input class="form-check-input" type="checkbox" value="ROLE_SELLER" id="role_seller" name="role[]">
                    {% endif%}

                    <label class="form-check-label" for="role_buyer">buyer</label>
                    {% if 'ROLE_BUYER' in user.roles %}
                    <input class="form-check-input" type="checkbox" value="ROLE_BUYER" id="role_buyer" name="role[]" checked>
                    {% else %}
                    <input class="form-check-input" type="checkbox" value="ROLE_BUYER" id="role_buyer" name="role[]">
                    {% endif%}

                </div>
                <button class="btn btn-primary" type="submit">submit</button>
                <a href="{{ path('app_user_index') }}">go back</a>
            </form>
        </main>
    </body>
{% endblock %}

templates/user/user_new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <body class="text-center">
        <main class="container">
            <h1>Register</h1>
            <form class="d-flex flex-column justify-content-center align-items-center" action="{{ path('app_user_create') }}" method="post">
                <div class="mb-3">
                    <label class="form-label" for="firstName">First name</label>
                    <input class="form-control" id="firstName" name="fistName">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="lastName">Last name</label>
                    <input class="form-control" id="lastName" name="lastName">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input class="form-control" type="email" id="email" name="email">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="password">Password</label>
                    <input class="form-control" type="password" id="password" name="password">
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="ROLE_SELLER" id="role_seller" name="role[]">
                    <label class="form-check-label" for="role_seller">Seller</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="ROLE_BUYER" id="role_buyer" name="role[]">
                    <label class="form-check-label" for="role_buyer">
                        Buyer
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="ROLE_ADMIN" id="role_admin" name="role[]">
                    <label class="form-check-label" for="role_admin">Admin</label>
                </div>
                <button class="btn btn-primary" type="submit">Submit</button>
                <a href="{{ path('app_login') }}">If you're already had a account</a>
            </form>
        </main>
    </body>
{% endblock %}

templates/user/user_show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <a href="{{ path('app_user_index') }}">go back</a>
        <p>{{ users.firstname }}</p>
        <p>{{ users.lastname }}</p>
        <p>{{ users.email }}</p>
        <p>{{ users.password }}</p>
        {% for role in users.roles %}
            <p>{{ role }}</p>
        {% endfor %}
        <a href="{{ path('app_user_delete', {id: users.id}) }}">
            Delete user
        </a>
    </div>
{% endblock %}